# Generated by Django 4.0.4 on 2022-04-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='supply_user',
        ),
    ]
