# Generated by Django 4.0.4 on 2022-05-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_alter_manager_user_name_alter_supplyuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='supplyuser',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
