# Generated by Django 4.0.4 on 2022-05-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_alter_manager_email_alter_supplyuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_description', models.TextField(max_length=255)),
                ('product_cost', models.FloatField()),
                ('product_quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
