# Generated by Django 4.0.3 on 2022-04-12 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_st_details_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_details',
            name='phoneno',
            field=models.IntegerField(blank=''),
        ),
        migrations.AlterField(
            model_name='st_details',
            name='rollno',
            field=models.CharField(blank='', help_text='Enter 4 digit roll number', max_length=4, unique=True),
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem1', models.FloatField(blank=True, null=True)),
                ('sem2', models.FloatField(blank=True, null=True)),
                ('sem3', models.FloatField(blank=True, null=True)),
                ('sem4', models.FloatField(blank=True, null=True)),
                ('sem5', models.FloatField(blank=True, null=True)),
                ('sem6', models.FloatField(blank=True, null=True)),
                ('sem7', models.FloatField(blank=True, null=True)),
                ('sem8', models.FloatField(blank=True, null=True)),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.st_details')),
            ],
        ),
    ]
