# Generated by Django 4.0.3 on 2022-04-13 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_st_details_phoneno_alter_st_details_rollno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='rollno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.st_details'),
        ),
    ]
