# Generated by Django 4.0.3 on 2022-04-14 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_marks_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_details',
            name='phoneno',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='st_details',
            name='profilepic',
            field=models.ImageField(blank=True, default='unknown.jpg', null=True, upload_to='uploads/'),
        ),
    ]
