# Generated by Django 4.0.3 on 2022-07-15 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0008_alter_activitylog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='date',
            field=models.DateField(db_column='Date', default=datetime.date(2022, 7, 15)),
        ),
    ]
